version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get -qq update
            apt-get install -y build-essential python python-dev python-pip
            pip install platformio
      - checkout
      - run:
          name: Build
          command: |
            cd firmware
            pio run -e v0 -e v1 -e v1_4players -t size
