#ifndef MEMORY_MAP_PAKET

#define MEMORY_MAP_PAKET

const int JEOPARDY_MEMORY_INIT_FLAG = 10;
const int JEOPARDY_MEMORY_NUM_PLAYERS = JEOPARDY_MEMORY_INIT_FLAG + 1;
const int JEOPARDY_MEMORY_CURRENT_QUESTION = JEOPARDY_MEMORY_NUM_PLAYERS + sizeof(short);
const int JEOPARDY_MEMORY_SCORES = JEOPARDY_MEMORY_CURRENT_QUESTION + sizeof(short);
const int JEOPARDY_MEMORY_ROUND = JEOPARDY_MEMORY_SCORES + PLAYER_COUNT * sizeof(short);

#endif
